#!/bin/bash

here=`pwd`
DIR_EVRT=$here/..

$DIR_EVRT/Tnum90.exe << ** > res
 &variables Old_Qtransfo=f nb_Qtransfo=3  /
 &Coord_transfo name_transfo='zmat' nat=3 /
1000.
1000. 1
1000. 1 2

 &Coord_transfo name_transfo='TwoD' nb_Transfo=1 /
   &TwoD name_2D='rho-s_x1-x2' list_TwoD_coord=1,2 /

 &Coord_transfo name_transfo='active' /
1 1 1

 &minimum  read_itQ0transfo=3 /
rho 1.4 bohr
s   -1000.  bohr
A  179.9999 °

 &calculation calc_Tnum=f calc_gG=t nderivGg=0 /
**

TnumOK=`tail -1 res | grep -c "END Tnum" `
if [ $TnumOK -ne "1" ]
then
 echo $0  1
 exit
fi


G11=`awk '/BEGINNING Write_dnMat/,/END Write_dnMat/ {print $2}' res | tail -14 | head -1`
G12=`awk '/BEGINNING Write_dnMat/,/END Write_dnMat/ {print $2}' res | tail -13 | head -1`


mO=29156.945687206524
mD=3671.4829394591770
mO=10000.
mD=1000.

err1=`echo $G11 $mO $mD | LANG=c awk '{print $1-(1/$2+1/$3)}'`
err2=`echo $G12 $mO | LANG=c awk '{print $1}'`

echo $0 $err1 $err2
