#!/bin/bash

./clean

LIST=`ls dat*`

#LIST=dat_jacobiOH2_RRu


i=0
for dat in $LIST
do
#  echo Tnum test: $dat
  ./$dat | LANG=c awk -f err_ana.awk >> err_Tnum
  tail -1 err_Tnum
  i=$((i+1))

  cat res >> res_all
done

nb_err=`grep -c "ERROR(s)" err_Tnum `
echo "ERROR(s) in "$i"-Tnum tests:" $nb_err
