#!/bin/bash

#remove the links
rm -f QDUtilLib AD_dnSVM EVRT_dnSVM nDindex 

for dirlib in *_loc
do
  echo $dirlib
  test -d $dirlib || continue
  cd $dirlib
  make --silent cleanall &> /dev/null
  cd ..
done

